[pytest]
filterwarnings =
    ignore:.*general_plain_validator_function.*:DeprecationWarning
    ignore:Support for class-based.*config.*:DeprecationWarning
    ignore:.*Failed to obtain server version.*:UserWarning
asyncio_mode = auto
